version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: todoapp_db
    environment:
      POSTGRES_USER: vivi
      POSTGRES_PASSWORD: vivi
      POSTGRES_DB: my_database
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: todoapp_app
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file: 
      - .env
    depends_on:
      - db

volumes:
  postgres_data: